/**
 * @description       : Apex Specialist Superbadge
 * @author            : Felipe Atamanczuk
 * @group             : 
 * @last modified on  : 11-04-2020
 * @last modified by  : Felipe Atamanczuk
 * Modifications Log 
 * Ver   Date         Author              Modification
 * 1.0   11-04-2020   Felipe Atamanczuk   Initial Version
**/
public with sharing class CaseDataFactory {
    public static Case createCasePositive (){
        //sem update/insert retorna o dado
    }
    public static List<Case> createCasePositive_bulk(){
        //fazer um for com o createpositive e preencher uma lista

    }
    public static Case createCaseNegative (){
        //sem update/insert retorna o dado
    }
   
}
