/**
 * @description       : 
 * @author            : Felipe Atamanczuk
 * @group             : 
 * @last modified on  : 10-30-2020
 * @last modified by  : Felipe Atamanczuk
 * Modifications Log 
 * Ver   Date         Author              Modification
 * 1.0   10-30-2020   Felipe Atamanczuk   Initial Version
**/
public with sharing class DTOCallout {
    public DTOCallout() {
        public String Status;
        public String Message;
        public String FirstName;
        public String LastName;
        public String Email;
        public String Phone;

    }
}
