/**
 * @description       : Apex Specialist Superbadge
 * @author            : Felipe Atamanczuk
 * @group             : 
 * @last modified on  : 11-04-2020
 * @last modified by  : Felipe Atamanczuk
 * Modifications Log 
 * Ver   Date         Author              Modification
 * 1.0   11-03-2020   Felipe Atamanczuk   Initial Version
**/
@isTest
public class MaintenanceRequestHelper_Test{
    static List<Case> caseLst = new List<Case> ();
    static List<Product2> prodLst = new List<Product2> ();
    static List<Work_Part__c> workpartLst = new List<Work_Part__c> ();

    
    @isTest
    public static void caseTrigger_positiveCase(){
        //criar dado, inserir, modificar, update

    } 
    
    @isTest
    public static void caseTrigger_negativeCase(){
        
    } 
    
    @isTest
    public static void caseTrigger_bulkCase(){
        
    } 


    
}